name: nodeseek鸡腿签到

on:
  workflow_dispatch:
  schedule:
    - cron: '15 17 * * *'  # 每天北京时间 01:15（UTC 17:15）

permissions:
  contents: read

jobs:
  run-nodeseek-sign:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'

      - name: install
        run: pip install requests

      - name: run
        env:
          COOKIE: ${{ secrets.COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TELEGRAM_API_URL: ${{ secrets.TELEGRAM_API_URL || 'https://api.telegram.org' }}
        run: python nodeseek_sign.py
